'use strict';
const assert = require('node:assert/strict');
const Store = require('./store.js');
assert.equal(Store.KEY, 'forge:studio-typographique:demo:v1');
assert.deepEqual(Store.FAMILIES, []);
assert.deepEqual(Store.PACKS, {});
const memory = Store.memoryStorage();
const client = Store.create(memory);
assert.deepEqual(client.read(), { version: 1, orders: [] });
assert.throws(() => client.addOrder({ id:'OE-DEMO-TEST', createdAt:'2026-07-18T12:00:00.000Z', family:'Famille rappelée', name:'Camille Exemple', email:'camille@example.test' }), /Catalogue fermé/);
assert.deepEqual(Store.create(memory).read(), { version: 1, orders: [] });
assert.equal(Store.create(memory).updateStatus('absente', 'Vérifiée'), null);
assert.deepEqual(Store.create(memory).reset(), { version: 1, orders: [] });
assert.deepEqual(Store.create(Store.memoryStorage({ version: 1, orders: [{ nope:true }] })).read(), { version: 1, orders: [] });
console.log('STORE PASS — allowlist et paquets vides, création refusée, récupération et reset fail-closed.');
