(()=>{'use strict';
const STORE_KEY='forge:forge-capital:demo:v1';
const RELEASE='cyber-ops-v1';
const MANDATE={venue:'HYPERLIQUID PERPS',doctrine:'ON-CHAIN ONLY',humanValidationRequired:false,browserSigning:false,execution:false,cexAccounts:false};
const clone=value=>JSON.parse(JSON.stringify(value));
const now=()=>new Date().toISOString();
const uid=prefix=>`${prefix}-${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).slice(2,6).toUpperCase()}`;
function baseline(){return {version:3,release:RELEASE,mandate:clone(MANDATE),capital:{authorized_usdt:100,received_usdt:0,liquid_usdt:0,invested_usdt:0,committed_usdt:0,net_value_usdt:0},transactions:[{id:'OBS-DEMO-001',title:'Observation initiale — fixture DÉMO',asset:'BTC/USDC',venue:'HYPERLIQUID PERPS',status:'DIFFÉRÉ',mode:'DÉMO',createdAt:'2026-07-13T22:23:05Z',proofId:'',proofSource:'',proofTimestamp:'',note:'Snapshot public différé, aucune activité ni exécution.'}],journal:[{id:'EVT-DEMO-001',at:'2026-07-13T22:23:05Z',type:'BASELINE',message:'Baseline ON-CHAIN ONLY chargée · 0 USDT reçu · aucune exécution.'}]};}
function valid(store){return Boolean(store&&store.version===3&&store.release===RELEASE&&store.mandate?.doctrine==='ON-CHAIN ONLY'&&Array.isArray(store.transactions)&&Array.isArray(store.journal)&&store.capital);}
function emit(store){if(typeof window.dispatchEvent==='function')window.dispatchEvent(new CustomEvent('forge-capital-change',{detail:clone(store)}));}
function saveStore(store){if(!valid(store))throw new Error('Store Forge Capital v3 invalide');localStorage.setItem(STORE_KEY,JSON.stringify(store));emit(store);return store;}
function loadStore(){try{const parsed=JSON.parse(localStorage.getItem(STORE_KEY));if(valid(parsed))return parsed;}catch(_error){}return saveStore(baseline());}
function resetStore(){return saveStore(baseline());}
function journal(store,type,message,refId=''){store.journal.unshift({id:uid('EVT'),at:now(),type,message,refId});}
function get(store,id){const item=store.transactions.find(row=>row.id===id);if(!item)throw new Error('Signal introuvable');return item;}
function createSignal({title,asset}){if(!String(title||'').trim()||!String(asset||'').trim())throw new Error('Titre et actif requis');const store=loadStore();const item={id:uid('SIG'),title:String(title).trim(),asset:String(asset).trim(),venue:'HYPERLIQUID PERPS',status:'OBSERVÉ',mode:'DÉMO',createdAt:now(),proofId:'',proofSource:'',proofTimestamp:'',note:''};store.transactions.unshift(item);journal(store,'SIGNAL_DEMO','Signal DÉMO créé localement, sans ordre ni signature.',item.id);saveStore(store);return clone(item);}
function studySignal(id,note){const store=loadStore(),item=get(store,id);item.status='ÉTUDIÉ';item.note=String(note||'Étude DÉMO sans capital réel.');item.studiedAt=now();journal(store,'ÉTUDE_DEMO','Signal marqué ÉTUDIÉ.',id);saveStore(store);return clone(item);}
function decideSignal(id,decision){if(!['PAPER','REJETÉ'].includes(decision))throw new Error('Décision DÉMO invalide');const store=loadStore(),item=get(store,id);if(item.status!=='ÉTUDIÉ')throw new Error('Étudiez le signal avant décision');item.status=decision;item.decidedAt=now();journal(store,`DÉCISION_${decision}`,`${decision} enregistré localement.`,id);saveStore(store);return clone(item);}
function createUnsignedTicket(id){const store=loadStore(),item=get(store,id);if(!['ÉTUDIÉ','PAPER'].includes(item.status))throw new Error('Étude requise avant ticket');item.status='TICKET À VALIDER';item.ticket={venue:'HYPERLIQUID PERPS',signed:false,transmitted:false,execution:false,mode:'DÉMO'};journal(store,'TICKET_NON_SIGNÉ','Ticket DÉMO créé : non signé, non transmis, non exécutable.',id);saveStore(store);return clone(item);}
function addProof(id,proofId,proofSource,proofTimestamp){const store=loadStore(),item=get(store,id);item.proofId=String(proofId||'').trim();item.proofSource=String(proofSource||'').trim();item.proofTimestamp=String(proofTimestamp||'').trim();if(!item.proofId||!item.proofSource)item.proofTimestamp='';if(item.proofId&&item.proofSource&&!item.proofTimestamp)item.proofTimestamp=now();journal(store,'PREUVE_DEMO','Preuve DÉMO attachée; elle ne prouve aucune transaction réelle.',id);saveStore(store);return clone(item);}
function updateStatus(id,status){const store=loadStore(),item=get(store,id);if(status==='EXÉCUTÉ AVEC PREUVE'&&(!item.proofId||!item.proofSource||!item.proofTimestamp))throw new Error('proofId, proofSource et proofTimestamp obligatoires');item.status=status;journal(store,'STATUT',`Statut ${status} enregistré.`,id);saveStore(store);return clone(item);}
function assertBaseline(){const store=loadStore();return {ok:store.transactions.length===1&&store.journal.length===1&&store.transactions[0].id==='OBS-DEMO-001',transactions:store.transactions.length,journal:store.journal.length};}
function escapeHTML(value){return String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));}
window.ForgeCapitalMatrix={STORE_KEY,RELEASE,MANDATE,baseline,loadStore,saveStore,resetStore,createSignal,studySignal,decideSignal,createUnsignedTicket,addProof,updateStatus,assertBaseline,escapeHTML};
})();
